# Generated by Django 3.0.4 on 2020-03-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backupserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('backupsvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupserver.BackupServer')),
            ],
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('start_time', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=250)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Server')),
            ],
        ),
    ]
