# Generated by Django 3.0.4 on 2020-03-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200309_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='backupsvr',
        ),
        migrations.DeleteModel(
            name='BackupJob',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
