# Generated by Django 3.0.4 on 2020-03-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backupserver', '0006_backupserver'),
        ('jobs', '0004_auto_20200320_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('backupsvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupserver.BackupServer')),
            ],
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('start_time', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Server')),
            ],
        ),
    ]
