# Generated by Django 3.0.4 on 2020-03-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_backupjob_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='backupsvr',
        ),
        migrations.DeleteModel(
            name='BackupJob',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
