# Generated by Django 3.0.4 on 2021-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_backupjob_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupjob',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
