# Generated by Django 3.0.4 on 2021-04-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210426_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
