# Generated by Django 3.0.4 on 2020-03-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupserver', '0002_auto_20200306_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupserver',
            name='application',
            field=models.CharField(default='', max_length=100),
        ),
    ]
