# Generated by Django 3.0.4 on 2020-03-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupserver', '0003_backupserver_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupserver',
            name='last_communication',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
