# Generated by Django 3.0.4 on 2020-03-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200320_1500'),
        ('backupserver', '0004_backupserver_last_communication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupServer',
        ),
    ]
