# Generated by Django 3.0.4 on 2020-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backupserver', '0005_delete_backupserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=100)),
                ('application', models.CharField(default='', max_length=100)),
                ('last_communication', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
