# Generated by Django 3.0.4 on 2020-03-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200320_1508'),
        ('backupserver', '0006_backupserver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupServer',
        ),
    ]
